### ISSUE TITLE
ProgressEvent's total is always 0 when the server is nginx and gzip is on

### ISSUE THREAD

**Issue by ShenJack** [seleb/chunk-progress-webpack-plugin#5]
Hi, I'm trying to use this plugin to provide progress awareness when loading a webpack chunk on demond, but I've met some trouble.

This plugin is really powerful and like a magic. Replacing webpack's JSONP with XHR indeed provide ProgressEvent when loading chunks. It works in my webpack local server.

But when I trying to use it on nginx to serve static files. **The ProgressEvent's total is always 0 when the  gzip is on.** Turing off gzip can still provide progress, but gzip is so important that we can't give up it.

```
{url: "App.e51936c7767d9620afb4.chunk.js", loaded: 65536, total: 0}
```

Then I notice that a gzipped response doesn't contain a **Content-Length** header, thus our XHR cannot calculate a total size.

We can use [Gzip Static Module](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html#gzip_static) to provide a content-length, this works in Firefox, but not in Chrome.

And it seems Chrome is not going to fix this bug 
[https://bugs.chromium.org/p/chromium/issues/detail?id=463622](https://bugs.chromium.org/p/chromium/issues/detail?id=463622)

**Comment by seleb** [comment]
Unfortunately fixing this seems to be outside the scope of this module since it's an issue with the server/browser, and afaik there isn't a feasible alternative to switch to. If `FetchObserver` ever gets standardized that could be a potential target for refactoring, but I think this will remain a known limitation for now.

(sorry for the super late response btw!)

**Comment by seleb** [comment]
forgot to close this when it was labelled wontfix earlier
